- name: install vim
  apt:
    pkg: vim
    state: installed
  tags: vim

- name: configure vim
  template:
    src: vimrc
    dest: /home/{{ username }}/.vimrc
  become: yes
  become_user: "{{ username }}"
  tags: vim

- apt_repository:
    repo: ppa:kelleyk/emacs
    state: present

- name: install emacs25-nox
  apt:
    pkg: emacs25-nox
    state: installed
  tags: emacs

- name: check for emacs config
  stat: path=/home/{{ username }}/.emacs.d
  register: emacs_config
  tags: emacs

- name: emacs config
  git:
    repo: https://github.com/garslo/emacs-config.git
    dest: /home/{{ username }}/.emacs.d
    accept_hostkey: yes
  become: yes
  become_user: "{{ username }}"
  when: emacs_config.stat.exists == False
