- hosts: devs
  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    - name: setup garslo user
      user: name=garslo groups=wheel append=yes state=present createhome=yes shell=/bin/bash
    - name: setup authorized_keys for garslo
      authorized_key: user=garslo key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCopdrPG2JWDobWxwbaX4ZUOCfa6nukdbAbrmgXBCySeOAe6vVSZ3kWs6I7TTrDllXRH/QCa/8Pmj1V/f+Q/AA+YRPMxYgUJcGeM0xgnyL/Cq3kRlEHnZXJnjZiMBLov5tT76jceEsLOvgmu0wZ4S8H5UkozFdh09+S1npV7qV/ocWb6YywcyrahO3VXBEqDw5HTlAv4sMmnqrorbY9ies4wTAVDJ1XWmXBwjqSg5wKtVgL/exZ5nwMfUuU1WWvH56eMt6hBvUbAofiJYlIlB5otz/5ofLt+5by3QfKe09zayMkDNo3yt9avw7U1ryRmal8i/RUe7x7c2iRBzeAuuLn gslopsema@llnw-mac"
    - name: check for emacs config
      stat: path=/home/garslo/.emacs.d
      register: emacs_config
    - name: emacs config
      git: repo=https://github.com/garslo/emacs-config.git dest=/home/garslo/.emacs.d accept_hostkey=yes
      become_user: garslo
      when: emacs_config.stat.exists == False
    - name: install tmux
      apt: pkg=tmux state=installed
    - name: configure tmux
      copy: src=files/tmux.conf dest=/home/garslo/.tmux.conf
    - name: install vim
      apt: pkg=vim state=installed
    - name: configure vim
      copy: src=files/vimrc dest=/home/garslo/.vimrc
    - name: install emacs24-nox
      apt: pkg=emacs24-nox state=installed
    - name: install git
      apt: pkg=git state=installed
    - name: configure git
      copy: src=files/gitconfig dest=/home/garslo/.gitconfig
    - name: make scratch directory
      become_user: garslo
      file: path=/home/garslo/scratch state=directory
    - name: check for existence of go
      stat: path=/usr/local/go/bin/go
      register: go
    - name: install go
      unarchive:
        src: https://storage.googleapis.com/golang/go1.7.3.linux-amd64.tar.gz
        dest: /usr/local
        copy: no
      when: go.stat.exists == False
    - name: symlink go binary
      file: src=/usr/local/go/bin/go dest=/usr/local/bin/go state=link
    - name: make scratch workspace
      file: path=/home/garslo/scratch-ws state=directory
    - name: go get goimports
      shell: GOPATH=/home/garslo/scratch-ws /usr/local/go/bin/go get golang.org/x/tools/cmd/goimports
    - name: symlink goimports
      file: src=/home/garslo/scratch-ws/bin/goimports dest=/usr/local/bin/goimports state=link
    - name: go get gocode
      shell: GOPATH=/home/garslo/scratch-ws /usr/local/go/bin/go get github.com/nsf/gocode
    - name: symlink gocode
      file: src=/home/garslo/scratch-ws/bin/gocode dest=/usr/local/bin/gocode state=link
    - name: install vpnc
      apt: pkg=vpnc state=installed
    - name: configure llnw vpn
      copy: src=files/llnw_vpn dest=/etc/vpnc/default.conf
    - name: set bashrc
      become_user: garslo
      copy: src=files/bashrc dest=/home/garslo/.bashrc
    - name: install jq
      apt: pkg=jq state=installed
    - name: install python-jedi
      apt: pkg=python-jedi state=installed
