- hosts: all
  gather_facts: False
  sudo: yes
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: playbook for an llnwdev box
  hosts: all
  remote_user: root
  sudo: yes
  vars:
    - username: garslo
  roles:
    - interactive
    - editors
    - godev
    - dev
    - llnwvpn
    - llnwdev
