- name: install some packages
  action: apt pkg={{ item }} state=present force=yes
  with_items:
    - lxd
    - python3-pip
    - build-essential
    - libssl-dev
    - ansible

- name: add user {{ username }} to lxd group
  user:
    name: "{{ username }}"
    groups: lxd
    append: true

- name: install lxdock
  pip: executable=/usr/bin/pip3 name=lxdock
  become_user: "{{ username }}"
  become: yes