- name: add private ssh key for llnw github
  template:
    src: llnw_github_private_key
    dest: /home/{{ username }}/.ssh/id_rsa

- name: add public ssh key for llnw github
  template:
    src: llnw_github_private_key.pub
    dest: /home/{{ username }}/.ssh/id_rsa.pub

- name: add apt repos
  action: apt_repository repo={{ item }} state=present
  with_items:
    - deb http://repo.llnw.net/lama/dev/ubuntu/precise binary/
    - deb http://debian.datastax.com/community stable main
    - deb http://repo.percona.com/apt trusty testing

- name: install dev packages
  action: apt pkg={{ item }} state=installed force=yes
  with_items:
    - go-dev-tools
    - cassandra=1.2.19
    - libjemalloc1
    # - percona-server-tokudb-5.6
    - mysql-server-5.5
    - libssl-dev
    - redis-server

- name: stop some daemon services
  action: service name={{ item }} state=stopped
  with_items:
    - cassandra
    - mysql
    - redis-server

- name: make /var/run/lama
  file:
    path: /var/run/lama
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
