- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: setup "{{ username }}" user
  user:
    name: "{{ username }}"
    groups: wheel
    append: yes
    state: present
    createhome: yes
    shell: /bin/bash

- name: setup authorized_keys for "{{ username }}"
  authorized_key:
    user: "{{ username }}"
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCopdrPG2JWDobWxwbaX4ZUOCfa6nukdbAbrmgXBCySeOAe6vVSZ3kWs6I7TTrDllXRH/QCa/8Pmj1V/f+Q/AA+YRPMxYgUJcGeM0xgnyL/Cq3kRlEHnZXJnjZiMBLov5tT76jceEsLOvgmu0wZ4S8H5UkozFdh09+S1npV7qV/ocWb6YywcyrahO3VXBEqDw5HTlAv4sMmnqrorbY9ies4wTAVDJ1XWmXBwjqSg5wKtVgL/exZ5nwMfUuU1WWvH56eMt6hBvUbAofiJYlIlB5otz/5ofLt+5by3QfKe09zayMkDNo3yt9avw7U1ryRmal8i/RUe7x7c2iRBzeAuuLn gslopsema@llnw-mac"

- name: setup authorized_keys for {{ username }} - 2
  authorized_key:
    user: "{{ username }}"
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3fskEj5w9e7PFv5vFvulbqijdJ/sOB7+45VxqngqHyihFkh+nOkTbvy+3tWbAl8223Ri7CPurrxmZ5L72ZkxwodVRMjayNpixAWqlGqfsar809W18J6BbJwr25b0rbIcSFSnmzTbm77vLjeuKEaOtByfJhBT63tr/Don6JV/I59NrJiAamBivRYG/rFqxAurxO5MQjsHPSYogWbvsiTnb6atTbaKt8nHFOF0nhgKBWrEophs7BucIUsPpaexPeUF2t8T9DuHfPTYfvkwNc6zcmv93GktVOSF3RmR4YVsqB1fMHaM8SueIWyasRDrgku0xSnrrKJ9DcjrEBOLhCARx {{ username }}@home-office"

- name: install some packages
  action: apt pkg={{item}} state=installed
  with_items:
    - tmux
    - htop

- name: configure tmux
  become: yes
  become_user: "{{ username }}"
  template:
    src: tmux.conf
    dest: /home/{{ username }}/.tmux.conf

- name: add git ppa
  apt_repository:
    repo: deb http://ppa.launchpad.net/git-core/ppa/ubuntu trusty main
    state: present

- name: install git
  apt:
    pkg: git
    state: installed
    force: yes

- name: configure git
  become: yes
  become_user: "{{ username }}"
  template:
    src: gitconfig
    dest: /home/{{ username }}/.gitconfig

- name: make scratch directory
  become: yes
  become_user: "{{ username }}"
  file:
    path: /home/{{ username }}/scratch
    state: directory

- name: set bashrc
  become: yes
  become_user: "{{ username }}"
  template:
    src: bashrc
    dest: /home/{{ username }}/.bashrc
