#!/bin/sh
#
# An example hook script to prepare the commit log message.
# Called by "git commit" with the name of the file that has the
# commit message, followed by the description of the commit
# message's source.  The hook's purpose is to edit the commit
# message file.  If the hook fails with a non-zero status,
# the commit is aborted.
#
# To enable this hook, rename this file to "prepare-commit-msg".

# This hook includes three examples.  The first comments out the
# "Conflicts:" part of a merge commit.
#
# The second includes the output of "git diff --name-status -r"
# into the message, just before the "git status" output.  It is
# commented because it doesn't cope with --amend or with squashed
# commits.
#
# The third example adds a Signed-off-by line to the message, that can
# still be edited.  This is rarely a good idea.

case "$2,$3" in
  merge,)
    /usr/bin/perl -i.bak -ne 's/^/# /, s/^# #/#/ if /^Conflicts/ .. /#/; print' "$1" ;;

  *)
      # its not a merge commit, so lets add our branch name if it matches the appropriate convention
      BRANCH=`git rev-parse --abbrev-ref HEAD`
      if expr "$BRANCH" : "\w\+-[0-9]\+" >> /dev/null
      then
          sed -i "1s/^\(\[[A-Z]\+-[0-9]\+\]\s*\)\?/[$BRANCH] /" "$1"
      fi
      ;;
esac
