- name: install vpnc
  apt:
    pkg: vpnc
    state: installed

- name: load llnw vpn secrets
  include_vars: llnw_vpn_vault.yaml
  no_log: true

- name: configure llnw vpn
  no_log: true
  template:
    src: llnw_vpn
    dest: /etc/vpnc/default.conf

- name: check if we are connected to the vpn
  ignore_errors: true
  command: pgrep vpnc
  register: vpnc

- name: connect to the vpn
  command: vpnc-connect
  when: vpnc.rc != 0