- name: install dev packages
  action: apt pkg={{ item }} state=installed force=yes
  with_items:
    - jq
    - python-jedi
    - python-pip
    - python-virtualenv
    - build-essential
    - libssl-dev

- name: mount /tmp as tmpfs
  mount:
    name: /tmp
    src: 'tmpfs'
    state: mounted
    fstype: tmpfs
    opts: 'size=4G'
