- name: install jq
  apt:
    pkg: jq
    state: installed

- name: install python-jedi
  apt:
    pkg: python-jedi
    state: installed

- name: mount /tmp as tmpfs
  mount:
    name: /tmp
    src: 'tmpfs'
    state: mounted
    fstype: tmpfs
    opts: 'size=4G'
